### ISSUE TITLE
Improve welcome menu UI

### ISSUE THREAD

**Issue by jbernardo95** [need-for-type/need-for-type#7]
Improve welcome menu UI with ASCII art.

Example: http://patorjk.com/software/taag/#p=display&f=Big&t=Need%20for%20Type

**Comment by tiagonbotelho** [comment]
I had that one but I think this one is better in the context of speed.

**Comment by jbernardo95** [comment]
My bad, I did start working on this one week ago, but didn't assign it to me.

**Comment by tiagonbotelho** [comment]
@jbernardo95 use this one http://patorjk.com/software/taag/#p=display&f=Slant&t=Need%20for%20Type

it's the one we use on the landing page and provides more context imo

**Comment by jbernardo95** [comment]
Done.
